spring:
  datasource:
    url: jdbc:mysql://182.92.76.127:3369/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zo_wms
    password: kekoukele
  redis:
    host: 39.107.193.187
    port: 6389
    password: j7@123456
  data:
    mongodb:
      uri: mongodb://awei:wms456_1@123.57.247.52:27000/firstDb